# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

from datetime import datetime

import sphinx_nefertiti

if sys.version_info < (3, 8):
    from importlib_metadata import version
else:
    from importlib.metadata import version

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

# -- Project information -----------------------------------------------------

proj_name = 'ds2mermaid'
# The full version, including alpha/beta/rc tags with setuptols-scm
# workaround for extra-long dirty version string
release = version(proj_name).split("+")[0]
# we don't need no steenkeeng short X.Y version.
version = release

project = "doorstop-to-mermaid"
author = 'Stephen L Arnold'
copyright = str(datetime.now().year) + f' {author}'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
description = 'Generate mermaid diagram source from a doorstop requirements document.'

# -- General configuration ------------------------------------------------

# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx_git',
    'sphinxcontrib.apidoc',
    'sphinx.ext.autodoc',
    'sphinx.ext.autodoc.typehints',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'myst_parser',
    'sphinx_nefertiti',
    #'sphinxcontrib.mermaid',
]
# do not render mermaid, show source instead
#myst_fence_as_directive = ["mermaid"]

myst_enable_extensions = [
    'amsmath',
    'attrs_block',
    'colon_fence',
    'deflist',
    'dollarmath',
    'fieldlist',
    'tasklist',
    'substitution',
]

myst_suppress_warnings = ["myst.header"]

# sphinxcontrib.apidoc
apidoc_module_dir = f'../../src/{proj_name}'
apidoc_output_dir = 'api'
apidoc_excluded_paths = ['scripts', 'tests']
apidoc_module_first = True
apidoc_include_private = True
apidoc_separate_modules = True

autodoc_typehints = 'description'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'data']

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = 'manni'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# test nefertiti settings
language = "en"
today_fmt = '%A %d. %B %Y, %H:%M'

html_theme = "sphinx_nefertiti"

html_theme_options = {
    "monospace_font_size": ".90rem",

    "style": "blue",
    "style_header_neutral": True,
    "pygments_light_style": "pastie",
    "pygments_dark_style": "dracula",

    "repository_url": f"https://github.com/sarnold/{project}",
    "repository_name": f"{project}",

    "current_version": "latest",
    "versions": [
        (f"v{version}", f"https://sarnold.github.io/{project}/"),
    ],

    "show_colorset_choices": True,
    # Return user's to 'blue' after a day since color was picked.
    "reset_colorset_choice_after_ms": 1000 * 60 * 60 * 24,
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = f'{proj_name}doc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ds2mermaid.tex', 'ds2mermaid Documentation', [author], 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'ds2mermaid', 'ds2mermaid Documentation', [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        'ds2mermaid',
        'ds2mermaid Documentation',
        [author],
        'ds2mermaid',
        description,
        'Miscellaneous',
    ),
]

